# .github/workflows/ci.yaml
name: Code_Checks

on: ["push", "pull_request"]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0']
        stability: [ prefer-stable ]
        include:
          - php: '8.0'
            stability: prefer-lowest
            symfony-version: 4.4
          - php: '8.0'
            symfony-version: 5.4
          - php: '8.1'
            symfony-version: 5.4
          - php: '8.2'
            symfony-version: 5.4
          - php: '8.2'
            symfony-version: 6.2

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} tests
    steps:
      # basically git clone
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      # use PHP of specific version
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pcov
          coverage: pcov

      - name: Install dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony-version }}
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require --no-progress --no-scripts --no-plugins symfony/flex
          composer update --no-interaction --prefer-dist --optimize-autoloader

      - name: Execute tests
        run: vendor/bin/phpunit -c ./phpunit.xml.dist ./tests --verbose
